# Generated by Django 5.0.6 on 2024-07-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_ordermodel_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='Hostel',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='block',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='room',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
