# Generated by Django 5.0.6 on 2024-07-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_hostel_ordermodel_hostel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
