# Generated by Django 5.0.6 on 2024-09-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_ordermodel_is_paid_alter_ordermodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
